name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: python3 -m pip install --upgrade pip && python3 -m pip install -e . && python3 -m pip install -r dev-requirements.txt && python3 -m pip install pyopenssl --upgrade
      - name: Run tests
        run: python3 -m pytest src/tests
  publish:
    name: "Publish in PyPi"
    runs-on: ubuntu-latest
    needs:
      - tests
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          pip3 install wheel twine
          python3 setup.py sdist bdist_wheel
          python3 -m twine check dist/*
          python3 -m twine upload --skip-existing dist/* --verbose -u ${USERNAME} -p ${PASSWORD}
